# ---Environment Configs---
env_name: jumanji
observation_attribute : board
flatten_observation: True
multi_agent : False

scenario:
  name: Game2048-v1
  task_name: game_2048

kwargs: {}

# Defines the metric that will be used to evaluate the performance of the agent.
# This metric is returned at the end of an experiment and can be used for hyperparameter tuning.
eval_metric: episode_return
