# ---CNN Networks---
actor_network:
  pre_torso:
    _target_: stoix.networks.torso.CNNTorso
    channel_sizes: [32, 32]
    kernel_sizes: [3, 3]
    strides: [1, 1]
    use_layer_norm: False
    activation: silu
  action_head:
    _target_: stoix.networks.heads.CategoricalHead

critic_network:
  pre_torso:
    _target_: stoix.networks.torso.CNNTorso
    channel_sizes: [32, 32]
    kernel_sizes: [3, 3]
    strides: [1, 1]
    use_layer_norm: False
    activation: silu
  critic_head:
    _target_: stoix.networks.heads.ScalarCriticHead
