# ---MLP SAC Networks---
actor_network:
  pre_torso:
    _target_: stoix.networks.torso.MLPTorso
    layer_sizes: [256, 256, 256, 256]
    use_layer_norm: False
    activation: silu
  action_head:
    _target_: stoix.networks.heads.NormalAffineTanhDistributionHead

q_network:
  input_layer:
    _target_: stoix.networks.inputs.ObservationActionInput
  pre_torso:
    _target_: stoix.networks.torso.MLPTorso
    layer_sizes: [256, 256, 256, 256]
    use_layer_norm: True
    activation: silu
  critic_head:
    _target_: stoix.networks.heads.ScalarCriticHead
